---

- name: Source redis dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - tcl
    state: present
  become: yes
  become_user: root

- name: clone redis repository
  ansible.builtin.git:
    repo: https://github.com/redis/redis.git
    dest: "{{ lookyloo_home }}/redis"
    version: 6.2
  become: yes
  become_user: "{{ lookyloo_user }}"

- name: build redis
  ansible.builtin.command: make
  args:
    chdir: "{{ lookyloo_home }}/redis"
    creates: "{{ lookyloo_home }}/redis/src/redis-server"
  become: yes
  become_user: "{{ lookyloo_user }}"
