---

- name: Source redis dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - tcl
    state: present
  become: yes
  become_user: root

- name: Clone valkey repository
  ansible.builtin.git:
    repo: https://github.com/valkey-io/valkey.git
    dest: "{{ lookyloo_home }}/valkey"
    version: "{{ lookyloo_valkey_version }}"
  become: yes
  become_user: "{{ lookyloo_user }}"

- name: Build valkey
  ansible.builtin.command: make
  args:
    chdir: "{{ lookyloo_home }}/valkey"
    creates: "{{ lookyloo_home }}/valkey/src/valkey-server"
  become: yes
  become_user: "{{ lookyloo_user }}"
