---

- name: Ensure systemd is present
  ansible.builtin.package:
    name: systemd
    state: present

- name: Configure uwhoisd systemd unit
  ansible.builtin.template:
    src: systemd-uwhoisd.service.j2
    dest: /etc/systemd/system/uwhoisd.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart uwhoisd

- name: Enable and start uwhoisd service
  ansible.builtin.service:
    name: uwhoisd
    state: started
    enabled: yes
  failed_when: false

- name: Ensure redis does not daemonize
  ansible.builtin.replace:
    dest: "{{ lookyloo_root }}/cache/cache.conf"
    regexp: "^daemonize .*"
    replace: "daemonize no"
    mode: '0644'
    owner: "{{ lookyloo_user }}"
    backup: "{{ lookyloo_backup }}"
  notify:
    - Restart lookyloo-redis

- name: Ensure redis-indexing does not daemonize
  ansible.builtin.replace:
    dest: "{{ lookyloo_root }}/indexing/indexing.conf"
    regexp: "^daemonize .*"
    replace: "daemonize no"
    mode: '0644'
    owner: "{{ lookyloo_user }}"
    backup: "{{ lookyloo_backup }}"
  notify:
    - Restart lookyloo-redis-indexing

- name: Configure lookyloo systemd units
  ansible.builtin.template:
    src: "systemd-{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
  notify:
    - Reload systemd
    - "Restart {{ item }}"
  loop: "{{ lookyloo_systemd_units }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start lookyloo services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ lookyloo_systemd_units }}"
