---

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart splash
  ansible.builtin.service:
    name: splash
    state: restarted
  become: yes
  become_user: root
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart uwhoisd
  ansible.builtin.service:
    name: uwhoisd
    state: restarted
  become: yes
  become_user: root
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart lookyloo
  ansible.builtin.service:
    name: lookyloo
    state: restarted
  become: yes
  become_user: root
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )
