---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  when:
    - not is_container|bool

- name: Restart splash
  ansible.builtin.service:
    name: splash
    state: restarted
  become: yes
  become_user: root
  when:
    - not is_container|bool

- name: Restart uwhoisd
  ansible.builtin.service:
    name: uwhoisd
    state: restarted
  become: yes
  become_user: root
  when:
    - not is_container|bool

- name: Restart lookyloo
  ansible.builtin.service:
    name: lookyloo
    state: restarted
  become: yes
  become_user: root
  when:
    - not is_container|bool
